---

version: "2"

volumes:
  mysqlData:
    driver: local

services:
  webserver:
    image: "nginx:1.11"
    links: ["php"]
    volumes:
      - "./Build/docker/nginx.conf:/etc/nginx/nginx.conf"
      - "./:/var/www/"
    env_file:
      - "./.env"
    environment:
      VIRTUAL_HOST: "${HOSTNAME}"
      VIRTUAL_PORT: 80
  php:
    image: simplyadmire/php
    command: "php-fpm7.0 -F"
    volumes:
      - "./Build/docker/php-fpm-pool.conf:/etc/php/7.0/fpm/pool.d/www.conf"
      - "./Build/docker/ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "./Build/docker/mailcatcher.ini:/etc/php/7.0/cli/conf.d/mailcatcher.ini"
      - "./:/var/www/"
    working_dir: "/var/www/"
    env_file:
      - "./.env"
    extra_hosts:
      - "${DOCKERMAINHOST}:docker"
    links:
      - "db"
  mailcatcher:
    image: "schickling/mailcatcher"
    environment:
      VIRTUAL_HOST: "mailcatcher.${HOSTNAME}"
      VIRTUAL_PORT: 1080
  db:
    image: "mariadb"
    env_file:
      - "./.env"
    volumes:
      - "mysqlData:/var/lib/mysql"
      - "./Build/docker/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf"
    ports:
      - "${MYSQL_PORT}:3306"
