---

-
  uriPattern: ''
  defaults:
    '@controller': 'Standard'
    '@action': 'index'

-
  uriPattern: 'dashboard'
  defaults:
    '@controller': 'Standard'
    '@action': 'dashboard'

-
  uriPattern: 'login'
  defaults:
    '@controller': 'Authentication'
    '@action': 'login'

-
  uriPattern: 'authenticate'
  defaults:
    '@controller': 'Authentication'
    '@action': 'authenticate'

-
  uriPattern: 'logout'
  defaults:
    '@controller': 'Authentication'
    '@action': 'logout'
