---

Neos:
  Flow:
    persistence:
      backendOptions:
        host: "%env:HOSTNAME%"
        port: "%env:MYSQL_PORT%"
        dbname: "%env:MYSQL_DATABASE%"
        user: "%env:MYSQL_USER%"
        password: "%env:MYSQL_PASSWORD%"
        driver: "pdo_mysql"
